#
# linux/arch/arm/fastfpe/Makefile
#
# Copyright (C) Peter Teichmann
#

obj-y	:=
obj-m	:=
obj-n	:=
obj-	:=

fastfpe-objs := module.o entry.o CPDO.o CPRT.o CPDT.o

obj-$(CONFIG_FPE_FASTFPE) += fastfpe.o
