#
# Makefile for drivers/telephony
#

obj-$(CONFIG_PHONE) += phonedev.o
obj-$(CONFIG_PHONE_IXJ) += ixj.o
obj-$(CONFIG_PHONE_IXJ_PCMCIA) += ixj_pcmcia.o
obj-$(CONFIG_ARCH_MV88f5181) += ../../arch/arm/mach-mv88fxx81/LSP/mv_phone/
